name: Publish slides
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Covert to html and pdf
        uses: KoharaKazuya/marp-cli-action@v2

      - uses: actions/upload-artifact@v3
        with:
          name: slides
          path: |
            docs
            images

      - uses: actions/upload-pages-artifact@v1
        with:
          path: |
            docs
            images

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
